version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=dev_secret_key
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - OPENAI_API_KEY=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
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
  
  celery:
    build: .
    command: celery -A doqment worker -l info
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=dev_secret_key
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - OPENAI_API_KEY=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
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
  
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: 