# Generated by Django 4.2.10 on 2025-03-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='template_type',
            field=models.CharField(choices=[('test_plan', 'テスト計画書'), ('test_specification', 'テスト仕様書'), ('test_report', 'テスト結果報告書'), ('custom', 'カスタム')], default='test_specification', max_length=50),
        ),
    ]
