# Generated by Django 4.2.10 on 2025-03-08 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_project_template_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', '待機中'), ('processing', '処理中'), ('completed', '完了'), ('failed', '失敗')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('total_sections', models.IntegerField(default=0)),
                ('completed_sections', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_tasks', to='documents.document')),
            ],
        ),
    ]
